import { Product } from '@/types/product';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    title: 'Precious Dog Horror Movie, Silence Lambs, Halloween T-Shirt',
    slug: 'precious-dog-horror-movie-silence-lambs-halloween-t-shirt',
    category: 'halloween',
    categoryLabel: 'Halloween',
    basePrice: 19.99,
    originalPrice: 29.99,
    frontImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&q=80',
    backImage: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&q=80',
    isSale: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 142,
    description: 'High quality graphic tee featuring iconic horror themes. Premium 100% cotton fabric.',
    variants: [
      { id: 'v1-1', sku: 'PDH-BLK-S', size: 'S', color: 'Black', productType: 'T-Shirt', price: 19.99, originalPrice: 29.99, stock: 50 },
      { id: 'v1-2', sku: 'PDH-BLK-M', size: 'M', color: 'Black', productType: 'T-Shirt', price: 19.99, originalPrice: 29.99, stock: 45 },
      { id: 'v1-3', sku: 'PDH-BLK-L', size: 'L', color: 'Black', productType: 'T-Shirt', price: 19.99, originalPrice: 29.99, stock: 30 },
      { id: 'v1-4', sku: 'PDH-BLK-XL', size: 'XL', color: 'Black', productType: 'T-Shirt', price: 21.99, originalPrice: 32.99, stock: 25 },
      { id: 'v1-5', sku: 'PDH-HOOD-L', size: 'L', color: 'Black', productType: 'Hoodie', price: 39.99, originalPrice: 53.99, stock: 15 },
    ],
  },
  {
    id: 'prod-2',
    title: 'Vintage Silence of the Lambs Shirt, Horror Tee, Buffalo Bill',
    slug: 'vintage-silence-of-the-lambs-shirt-horror-tee-buffalo-bill',
    category: 'horror',
    categoryLabel: 'Horror Movie',
    basePrice: 19.99,
    originalPrice: 29.99,
    frontImage: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&q=80',
    backImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&q=80',
    isSale: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 98,
    description: 'Retro vintage styled graphic tee printed on ultra soft fabric.',
    variants: [
      { id: 'v2-1', sku: 'VSL-NVY-S', size: 'S', color: 'Navy', productType: 'T-Shirt', price: 19.99, originalPrice: 29.99, stock: 40 },
      { id: 'v2-2', sku: 'VSL-NVY-M', size: 'M', color: 'Navy', productType: 'T-Shirt', price: 19.99, originalPrice: 29.99, stock: 35 },
      { id: 'v2-3', sku: 'VSL-HOOD-M', size: 'M', color: 'Navy', productType: 'Hoodie', price: 42.99, originalPrice: 59.99, stock: 20 },
    ],
  },
  {
    id: 'prod-3',
    title: 'Ella Langley Country Music Retro Graphic Tee',
    slug: 'ella-langley-country-music-retro-graphic-tee',
    category: 'ella-langley',
    categoryLabel: 'Ella Langley',
    basePrice: 22.99,
    originalPrice: 34.99,
    frontImage: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600&q=80',
    backImage: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&q=80',
    isSale: true,
    isFeatured: true,
    rating: 5.0,
    reviewCount: 215,
    description: 'Trending Ella Langley tour graphic tee for country music fans.',
    variants: [
      { id: 'v3-1', sku: 'EL-WHT-S', size: 'S', color: 'White', productType: 'T-Shirt', price: 22.99, originalPrice: 34.99, stock: 60 },
      { id: 'v3-2', sku: 'EL-WHT-M', size: 'M', color: 'White', productType: 'T-Shirt', price: 22.99, originalPrice: 34.99, stock: 50 },
      { id: 'v3-3', sku: 'EL-WHT-L', size: 'L', color: 'White', productType: 'T-Shirt', price: 22.99, originalPrice: 34.99, stock: 40 },
    ],
  },
  {
    id: 'prod-4',
    title: 'Vintage Classic Truck & Muscle Car Enthusiast Shirt',
    slug: 'vintage-classic-truck-muscle-car-enthusiast-shirt',
    category: 'car-truck',
    categoryLabel: 'Car & Truck',
    basePrice: 24.99,
    originalPrice: 36.99,
    frontImage: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&q=80',
    backImage: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600&q=80',
    isSale: false,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 64,
    description: 'Custom vintage car illustration printed with vibrant long-lasting ink.',
    variants: [
      { id: 'v4-1', sku: 'VCT-BLK-M', size: 'M', color: 'Black', productType: 'T-Shirt', price: 24.99, stock: 30 },
      { id: 'v4-2', sku: 'VCT-BLK-L', size: 'L', color: 'Black', productType: 'T-Shirt', price: 24.99, stock: 25 },
    ],
  },
  {
    id: 'prod-5',
    title: 'Morgan Wallen One Thing At A Time Country Tour Tee',
    slug: 'morgan-wallen-one-thing-at-a-time-country-tour-tee',
    category: 'morgan-wallen',
    categoryLabel: 'Morgan Wallen',
    basePrice: 23.99,
    originalPrice: 35.00,
    frontImage: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&q=80',
    backImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&q=80',
    isSale: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 310,
    description: 'Exclusive Morgan Wallen fan apparel printed on heavy cotton.',
    variants: [
      { id: 'v5-1', sku: 'MW-BLK-S', size: 'S', color: 'Dark Heather', productType: 'T-Shirt', price: 23.99, originalPrice: 35.00, stock: 45 },
      { id: 'v5-2', sku: 'MW-BLK-M', size: 'M', color: 'Dark Heather', productType: 'T-Shirt', price: 23.99, originalPrice: 35.00, stock: 40 },
    ],
  },
  {
    id: 'prod-6',
    title: 'Best Line Of Blazing Saddles Wall Calendar 2027',
    slug: 'best-line-of-blazing-saddles-wall-calendar-2027',
    category: 'vintage',
    categoryLabel: 'Vintage 80s/90s',
    basePrice: 24.99,
    originalPrice: 40.00,
    frontImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&q=80',
    backImage: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&q=80',
    isSale: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 42,
    description: 'Full color 12-month wall calendar with high resolution retro artwork.',
    variants: [
      { id: 'v6-1', sku: 'CAL-2027', size: 'Standard', color: 'Multicolor', productType: 'Wall Calendar', price: 24.99, originalPrice: 40.00, stock: 100 },
    ],
  },
  {
    id: 'prod-7',
    title: 'Silence of The Lambs Shirt, Buffalo Shirt, Movie Tshirt, For Man, For Women #170',
    slug: 'silence-of-the-lambs-shirt-buffalo-shirt-movie-tshirt-for-man-for-women-170',
    category: 'horror',
    categoryLabel: 'Horror Movie',
    basePrice: 19.99,
    originalPrice: 29.99,
    frontImage: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&q=80',
    backImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&q=80',
    isSale: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 170,
    description: 'Silence of the Lambs Buffalo Bill graphic tee. Custom printed on high quality 100% cotton fabric.',
    variants: [
      { id: 'v7-1', sku: 'SLB-BLK-S', size: 'S', color: 'Black', productType: 'T-Shirt', price: 19.99, originalPrice: 29.99, stock: 50 },
      { id: 'v7-2', sku: 'SLB-BLK-M', size: 'M', color: 'Black', productType: 'T-Shirt', price: 19.99, originalPrice: 29.99, stock: 45 },
      { id: 'v7-3', sku: 'SLB-HOOD-L', size: 'L', color: 'Black', productType: 'Hoodie', price: 39.99, originalPrice: 53.99, stock: 20 },
    ],
  },
];
